<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Infinite.Core.Postgres" Version="{{versao}}" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="{{versao}}" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="{{versao}}" />
    <PackageReference Include="Riok.Mapperly" Version="{{versao}}" />
    <PackageReference Include="FluentValidation" Version="{{versao}}" />
    <!-- Só quando houver cliente HTTP externo: -->
    <!-- <PackageReference Include="Refit" Version="{{versao}}" /> -->
  </ItemGroup>

</Project>
